Add AuthentificationViewControllerwith all tasks except margin indent…
JuliaRuru/heads-auto-layout pull request #1
Opened 2022-04-16 18:24 UTC by JuliaRuru

…ation

2022-04-18 08:07 UTC, NosferatuHnH requested changes

2022-04-18 08:07 UTC, NosferatuHnH commented on hnh1/AuthentificationViewController.swift
> +        self.loginTextField.becomeFirstResponder()
селф не нужен, лучше этот метод вызывать после того, как вью показалось

2022-04-18 08:07 UTC, NosferatuHnH commented on hnh1/AuthentificationViewController.swift
> +    @IBOutlet weak var passwordTextField2: UITextField!
Лучше писать имя по смыслу passwordTextField2 -> passwordConfirmTextField

2022-04-18 08:07 UTC, NosferatuHnH commented on hnh1/AuthentificationViewController.swift
> +            self.passwordTextField2.becomeFirstResponder()
self не нужен

2022-04-18 08:07 UTC, NosferatuHnH commented on hnh1/AuthentificationViewController.swift
> +class MyButton: UIButton {
1) В отдельный файл. 2) Название класса не лучшее, Можно назвать мерцающей кнопкой ну или на худой конец кастомной.

2022-04-18 08:07 UTC, NosferatuHnH commented on hnh1/ViewController.swift
>  class ViewController: UIViewController {
Переименуй

2022-04-18 09:28 UTC, JuliaRuru commented on hnh1/AuthentificationViewController.swift
> +        self.loginTextField.becomeFirstResponder()
Убрала

2022-04-18 09:28 UTC, JuliaRuru commented on hnh1/AuthentificationViewController.swift
> +    @IBOutlet weak var passwordTextField2: UITextField!
Переименовала

2022-04-18 09:29 UTC, JuliaRuru commented on hnh1/AuthentificationViewController.swift
> +            self.passwordTextField2.becomeFirstResponder()
Исправила, забыла отразить в названии коммита

2022-04-18 09:39 UTC, JuliaRuru commented on hnh1/AuthentificationViewController.swift
> +class MyButton: UIButton {
Переименовала, перенесла класс кнопки в отдельный файл

2022-04-18 12:25 UTC, JuliaRuru commented on hnh1/ViewController.swift
>  class ViewController: UIViewController {
Готово

2022-04-19 06:49 UTC, NosferatuHnH requested changes

2022-04-19 06:49 UTC, NosferatuHnH commented on flickeringButton.swift
> +class flickeringButton: UIButton {
Название класса с большой буквы

2022-04-19 06:49 UTC, NosferatuHnH commented on hnh1/RegistrationViewController.swift
> +//#Mark: placeholder style
ненужная пометка

2022-04-19 06:49 UTC, NosferatuHnH commented on hnh1/RegistrationViewController.swift
> +        passwordConfirmTextField.attributedPlaceholder = NSAttributedString(string: "    Повторите пароль", attributes: attributes)
не самый лучший подход. Есть лучше

2022-04-19 06:57 UTC, JuliaRuru commented on hnh1/RegistrationViewController.swift
> +//#Mark: placeholder style
ОК

2022-04-19 06:59 UTC, JuliaRuru commented on flickeringButton.swift
> +class flickeringButton: UIButton {
Изменила

2022-04-20 08:34 UTC, JuliaRuru commented on hnh1/RegistrationViewController.swift
> +        passwordConfirmTextField.attributedPlaceholder = NSAttributedString(string: "    Повторите пароль", attributes: attributes)
Исправила. Так лучше?

2022-04-21 05:54 UTC, NosferatuHnH requested changes

2022-04-21 05:54 UTC, NosferatuHnH commented on hnh1/RegistrationViewController.swift
> +        let attributes = [ NSAttributedString.Key.foregroundColor: UIColor.black,
[ NSAttr - зачем пробел?

2022-04-21 19:01 UTC, JuliaRuru commented on hnh1/RegistrationViewController.swift
> +        let attributes = [ NSAttributedString.Key.foregroundColor: UIColor.black,
Опечатка) убрала

2022-04-21 19:17 UTC, merged