Home work3
JuliaRuru/heads-auto-layout pull request #2
Opened 2022-04-23 10:31 UTC by JuliaRuru

2022-04-23 19:10 UTC, NosferatuHnH requested changes

2022-04-23 19:10 UTC, NosferatuHnH commented on hnh1/AuthentificationViewController.swift
> -}
зачем выставление фрейма в 0 у вьюхи? Зачем пустая строка?

2022-04-23 19:10 UTC, NosferatuHnH commented on hnh1/AuthentificationViewController.swift
> +    @objc func keybrdDiDHide() {
пропустила букву и метод на WillHide таки

2022-04-23 19:10 UTC, NosferatuHnH commented on hnh1/AuthentificationViewController.swift
> +    @objc func keybrdDidChange(sender: Notification) {
тоже пропуск буквы, тоже вилл

2022-04-23 19:10 UTC, NosferatuHnH commented on hnh1/AuthentificationViewController.swift
> +        print("Animation time of keyboard =", timeAnimation)
тут гард не нужен. Независимо от того пришло время или нет - надо делать дальше. Иф лет подойдёт больше

2022-04-23 19:10 UTC, NosferatuHnH commented on hnh1/AuthentificationViewController.swift
> +        }
объедени

```
guard let keybrdFrame: NSValue = sender.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue, 
      let activeField = activeField
          else {
          return
          }
```

Условия можно перечислять через запятую

2022-04-23 19:10 UTC, NosferatuHnH commented on hnh1/RegistrationViewController.swift
> +    override func viewWillDisappear(_ animated: Bool) {
отбей строчку между методами

2022-04-23 19:10 UTC, NosferatuHnH commented on hnh1/RegistrationViewController.swift
> +    @objc func keybrdDidChange(sender: Notification) {
те же замечания, что к прошлым методам

2022-04-24 09:28 UTC, JuliaRuru commented on hnh1/AuthentificationViewController.swift
> -}
Сорян, игралась с разным и случайно оставила лишнюю строку. Убрала

2022-04-24 09:29 UTC, JuliaRuru commented on hnh1/AuthentificationViewController.swift
> +    @objc func keybrdDiDHide() {
Мне казалось, что метод можно назвать как угодно. Пока исправила и почитаю еще

2022-04-24 09:29 UTC, JuliaRuru commented on hnh1/AuthentificationViewController.swift
> +    @objc func keybrdDidChange(sender: Notification) {
Исправила

2022-04-24 09:29 UTC, JuliaRuru commented on hnh1/AuthentificationViewController.swift
> +        print("Animation time of keyboard =", timeAnimation)
OK

2022-04-24 09:29 UTC, JuliaRuru commented on hnh1/AuthentificationViewController.swift
> +        }
Готово

2022-04-24 09:29 UTC, JuliaRuru commented on hnh1/RegistrationViewController.swift
> +    override func viewWillDisappear(_ animated: Bool) {
+

2022-04-24 09:29 UTC, JuliaRuru commented on hnh1/RegistrationViewController.swift
> +    @objc func keybrdDidChange(sender: Notification) {
Исправила

2022-04-24 16:32 UTC, NosferatuHnH requested changes

2022-04-24 16:32 UTC, NosferatuHnH commented on hnh1/AuthentificationViewController.swift
> +        }
зачем элс? Гард как раз убирали чтоб от ретурна уйти.

2022-04-24 16:39 UTC, JuliaRuru commented on hnh1/AuthentificationViewController.swift
> +        }
Готово. Тупанула

2022-04-24 16:44 UTC, NosferatuHnH approved these changes

2022-04-24 17:02 UTC, merged