Home work4
JuliaRuru/heads-auto-layout pull request #3
Opened 2022-05-09 21:44 UTC by JuliaRuru

2022-05-10 20:29 UTC, NosferatuHnH requested changes

2022-05-10 20:29 UTC, NosferatuHnH commented on hnh1/Assets.xcassets/rectangle.imageset/Contents.json
> +      "filename" : "photo.png",
это фото в дизе просто для примера. Его точно ни куда не надо вставлять

2022-05-10 20:29 UTC, NosferatuHnH commented on hnh1/Assets.xcassets/square.imageset/Contents.json
> +      "filename" : "image.png",
и это тоже. Тем более это одно фото

2022-05-10 20:29 UTC, NosferatuHnH commented on hnh1/ProfileViewController.swift
> +        return CGFloat(height)
для чистоты загони все магические числа в константы. Енам / структура / лет переменные

2022-05-10 20:29 UTC, NosferatuHnH commented on hnh1/ProfileViewController.swift
> +            }
через свитч красивее

2022-05-10 20:29 UTC, NosferatuHnH commented on hnh1/ProfileViewController.swift
> +            return UITableViewCell()
чуть съехало - оно на уровне с ифом

2022-05-12 20:02 UTC, JuliaRuru commented on hnh1/ProfileViewController.swift
> +            }
Заменила на свитч. Не знаю насколько красивее получилось, но все же

2022-05-12 20:04 UTC, JuliaRuru commented on hnh1/ProfileViewController.swift
> +            return UITableViewCell()
Эта часть почила вместе с ифом

2022-05-15 16:51 UTC, JuliaRuru commented on hnh1/Assets.xcassets/rectangle.imageset/Contents.json
> +      "filename" : "photo.png",
OK

2022-05-15 16:51 UTC, JuliaRuru commented on hnh1/Assets.xcassets/square.imageset/Contents.json
> +      "filename" : "image.png",
OK

2022-05-15 16:51 UTC, JuliaRuru commented on hnh1/ProfileViewController.swift
> +        return CGFloat(height)
Так ты имел ввиду?

2022-05-17 11:11 UTC, NosferatuHnH commented on hnh1/Assets.xcassets/square.imageset/Contents.json
> +      "filename" : "image.png",
А сами фото гит показывает что ещё в репозитории

2022-05-17 11:17 UTC, NosferatuHnH requested changes

2022-05-17 11:17 UTC, NosferatuHnH commented on hnh1/ProfileViewController.swift
> +        }
не внутри функции, а внутри класса. На уроке смотрели.

2022-05-17 11:17 UTC, NosferatuHnH commented on hnh1/ProfileViewController.swift
> +        }
И в названии как-то надо указать, что это константы ConstantValues если хочется вэлью в название тиснуть

2022-05-17 15:31 UTC, JuliaRuru commented on hnh1/Assets.xcassets/square.imageset/Contents.json
> +      "filename" : "image.png",
Убрала

2022-05-17 15:49 UTC, JuliaRuru commented on hnh1/ProfileViewController.swift
> +        }
Готово

2022-05-18 18:40 UTC, NosferatuHnH approved these changes

2022-05-18 18:44 UTC, merged