Home work5
JuliaRuru/heads-auto-layout pull request #4
Opened 2022-05-29 08:17 UTC by JuliaRuru

2022-05-29 18:02 UTC, NosferatuHnH requested changes

2022-05-29 18:02 UTC, NosferatuHnH commented on Services/NetworkManager.swift
> +
пустая строка

2022-05-29 18:02 UTC, NosferatuHnH commented on Services/NetworkManager.swift
> +                                            "password": password]
вынеси в стуктуру, поддерживающую Энкодабл

2022-05-29 18:02 UTC, NosferatuHnH commented on Services/NetworkManager.swift
> +            headers: nil,
сотри. Не нужны

2022-05-29 18:02 UTC, NosferatuHnH commented on ViewControllers/AuthentificationViewController.swift
> +    let storageManager = StorageManager()
закрой протоколом на манер NetworkManager'а и доставай из сервис локатора

2022-05-29 18:02 UTC, NosferatuHnH commented on ViewControllers/AuthentificationViewController.swift
> +            }
раз текст ошибки игноришь, то под гардом доставай данные. Если токен или юзер аийди не пришло, то авторизация явно провалилась и можно рассказать об этом

2022-05-29 18:02 UTC, NosferatuHnH commented on ViewControllers/AuthentificationViewController.swift
> +        show(tabBarController, sender: self)
хотя бы презент

2022-05-29 18:02 UTC, NosferatuHnH commented on ViewControllers/AuthentificationViewController.swift
> +        show(registrationViewController, sender: self)
аналогично

2022-05-29 18:02 UTC, NosferatuHnH commented on ViewControllers/PlanetViewController.swift
> +
или "// TODO: что-то там" метка или убирай пустой метод

2022-05-29 18:02 UTC, NosferatuHnH commented on ViewControllers/ProfileViewController.swift
> +    let storageManager = StorageManager()
протокол - доставай из СЛ

2022-05-29 18:02 UTC, NosferatuHnH commented on ViewControllers/RegistrationViewController.swift
> +    let storageManager = StorageManager()
и тут

2022-05-29 18:02 UTC, NosferatuHnH commented on ViewControllers/RegistrationViewController.swift
> +                if self?.passwordTextField.text != self?.passwordConfirmTextField.text {
вынеси проверку выше. Интернет - запрос нам не нужен, если пароли не совпали

2022-05-29 18:02 UTC, NosferatuHnH commented on ViewControllers/RegistrationViewController.swift
>          show(tabBarController, sender: self)
презент?

2022-05-29 18:02 UTC, NosferatuHnH commented on ViewControllers/RegistrationViewController.swift
> +        let group = DispatchGroup()
зачем?

2022-05-29 18:02 UTC, NosferatuHnH commented on hnh1/AppDelegate.swift
> +        let storageManager = StorageManager()
под протокол. Из локатора.

2022-05-29 20:31 UTC, JuliaRuru commented on Services/NetworkManager.swift
> +
fixed

2022-05-29 20:31 UTC, JuliaRuru commented on Services/NetworkManager.swift
> +            headers: nil,
OK

2022-05-29 20:35 UTC, JuliaRuru commented on Services/NetworkManager.swift
> +                                            "password": password]
Метод принимает словарь строк

2022-05-29 21:16 UTC, JuliaRuru commented on ViewControllers/AuthentificationViewController.swift
> +    let storageManager = StorageManager()
Готово

2022-05-29 21:16 UTC, JuliaRuru commented on ViewControllers/ProfileViewController.swift
> +    let storageManager = StorageManager()
Сделала

2022-05-29 21:17 UTC, JuliaRuru commented on ViewControllers/RegistrationViewController.swift
> +    let storageManager = StorageManager()
И тут

2022-05-29 21:17 UTC, JuliaRuru commented on hnh1/AppDelegate.swift
> +        let storageManager = StorageManager()
fixed

2022-05-29 21:20 UTC, JuliaRuru commented on ViewControllers/RegistrationViewController.swift
> +        let group = DispatchGroup()
чтобы юзернэйм и юзерайди сохранялись в кичейн после их получения, а не как получится

2022-05-29 21:29 UTC, JuliaRuru commented on ViewControllers/AuthentificationViewController.swift
> +        show(tabBarController, sender: self)
Поменяла

2022-05-29 21:29 UTC, JuliaRuru commented on ViewControllers/AuthentificationViewController.swift
> +        show(registrationViewController, sender: self)
Тоже поменяла

2022-05-29 21:29 UTC, JuliaRuru commented on ViewControllers/RegistrationViewController.swift
>          show(tabBarController, sender: self)
презент

2022-05-29 21:30 UTC, JuliaRuru commented on ViewControllers/RegistrationViewController.swift
> +        let group = DispatchGroup()
вернее токен и юзерайди

2022-05-29 21:34 UTC, JuliaRuru commented on ViewControllers/RegistrationViewController.swift
> +                if self?.passwordTextField.text != self?.passwordConfirmTextField.text {
Я наоборот решила раньше времени юзера не дергать с паролями, если он имя кривое написал. Может, пока будет новое думать, исправит пароли

2022-05-29 21:41 UTC, JuliaRuru commented on ViewControllers/PlanetViewController.swift
> +
Поняла

2022-05-29 22:04 UTC, JuliaRuru commented on ViewControllers/AuthentificationViewController.swift
> +            }
Готово

2022-05-30 10:20 UTC, NosferatuHnH commented on ViewControllers/AuthentificationViewController.swift
> +    let storageManager = ServiceLocator.keychainStorageManager()
keychainStorageManager протокол уммеет 1) чистить связку ключей 2) сохранять данные по любым ключам 3) грузить данные по любым ключам.

Что должен уметь местный сторадж менеджер? схранять токен. Схранять юзерайди. Зачем ему знать остальное. Сразу скажу на будущее, что по другим местам так же.

2022-05-30 10:22 UTC, NosferatuHnH commented on ViewControllers/AuthentificationViewController.swift
> +    @IBAction func registerButtonClick(_ sender: Any) { goToRegistration() }
почему не тут реализовать функции? Зачем так выносить?

2022-05-30 10:25 UTC, NosferatuHnH commented on ViewControllers/RegistrationViewController.swift
> +                if self?.passwordTextField.text != self?.passwordConfirmTextField.text {
Фишка в том, что всё может быть идеально, а пароли не совпали - тогда был лишний запрос на бэк. Дудосить бэк - плохо

2022-05-30 10:26 UTC, NosferatuHnH commented on ViewControllers/RegistrationViewController.swift
> +        let group = DispatchGroup()
То есть ты думаешь, что ответ с бэка придёт раньше, чем был послан запрос?)

2022-05-30 16:42 UTC, JuliaRuru commented on ViewControllers/RegistrationViewController.swift
> +                if self?.passwordTextField.text != self?.passwordConfirmTextField.text {
ок, не буду так, исправила

2022-05-30 17:08 UTC, JuliaRuru commented on ViewControllers/RegistrationViewController.swift
> +        let group = DispatchGroup()
А, ну, это я пыталась решить проблему, которая была в другом)) убрала

2022-05-30 17:21 UTC, JuliaRuru commented on ViewControllers/AuthentificationViewController.swift
> +    let storageManager = ServiceLocator.keychainStorageManager()
Ты имеешь ввиду зачем ему знать юзернэйм? Или в функции ограничить его возможности только сохранением токена и юзерайди?

2022-05-30 19:21 UTC, JuliaRuru commented on ViewControllers/AuthentificationViewController.swift
> +    let storageManager = ServiceLocator.keychainStorageManager()
Fixed

2022-05-30 19:32 UTC, JuliaRuru commented on ViewControllers/AuthentificationViewController.swift
> +    @IBAction func registerButtonClick(_ sender: Any) { goToRegistration() }
Мне показалось более читаемым. Исправила.

2022-06-02 18:10 UTC, NosferatuHnH requested changes

2022-06-02 18:10 UTC, NosferatuHnH commented on Services/NetworkManager/LocationNetworkManager.swift
> +//    func getCharacterList(url: String, completion: ((CharacterListResponse?, Error?) -> ())?)
коммент

2022-06-02 18:10 UTC, NosferatuHnH commented on Services/StorageManager/ProfileStorageManager.swift
> +    func loadFromKeychain(key: StorageManager.StorageManagerKey) -> String?
так профиль сможет загрузить из кейчейна по notFirstLaunch и userId ключам. Зачем? Почему нельзя сделать метод userId() -> Стринг и получать конкретно нужную часть?

2022-06-02 18:10 UTC, NosferatuHnH commented on Services/StorageManager/StorageManager.swift
> +import KeychainAccess
или шаримся в кейчейне тут (метод) или пустой импорт убрать

2022-06-02 18:10 UTC, NosferatuHnH commented on Services/StorageManager/UserDefaultsStorageManager.swift
> +    func userDefaultsBool(key: StorageManager.StorageManagerKey) -> Bool
и снова - зачем по ключам когда можно конкретный метод hasFirstLaunch() -> Bool  и setHasFirstLaunch() ?

2022-06-02 18:10 UTC, NosferatuHnH commented on ViewControllers/LocationCells/LocationTableViewCell.swift
> +    }
пустые методы

2022-06-02 18:10 UTC, NosferatuHnH commented on ViewControllers/LocationViewController.swift
> +        return CGFloat(height)
просто 58 и больше ни чего не надо

2022-06-02 18:10 UTC, NosferatuHnH commented on ViewControllers/LocationViewController.swift
> +        progressHUD.show(in: self.view)
показывать только при первой загрузке. Остальные в фоне подтягиваются

2022-06-02 18:10 UTC, NosferatuHnH commented on ViewControllers/RegistrationViewController.swift
> +
пустая строка

2022-06-02 18:10 UTC, NosferatuHnH commented on ViewControllers/ResidentsViewController.swift
> +        requestCharacterQueue.maxConcurrentOperationCount = 10
убирай)

2022-06-02 18:10 UTC, NosferatuHnH commented on ViewControllers/ResidentsViewController.swift
> +        group.enter()
зачем?

2022-06-02 18:10 UTC, NosferatuHnH commented on ViewControllers/ResidentsViewController.swift
> +         if let cell = collectionView.dequeueReusableCell(withReuseIdentifier: ResidentsCollectionViewCell.className, for: indexPath) as? ResidentsCollectionViewCell {
не вижу загрузки на ячейке, не вижу гарантий, что подгрузили и засунули в ячейку именно то, что надо

2022-06-02 18:10 UTC, NosferatuHnH commented on hnh1/AppDelegate.swift
> +        }
appDelegateStorageManager()

2022-06-02 18:10 UTC, NosferatuHnH commented on ViewControllers/ResidentsViewController.swift
> +            heightDimension: .absolute(187))
раньше было лучше

2022-06-02 19:00 UTC, NosferatuHnH commented on ViewControllers/profileCells/ProfileColorTableViewCell.swift
> +import EFColorPicker
вот он лишний

2022-06-02 19:16 UTC, JuliaRuru commented on ViewControllers/profileCells/ProfileColorTableViewCell.swift
> +import EFColorPicker
убрала

2022-06-02 20:18 UTC, JuliaRuru commented on ViewControllers/ResidentsViewController.swift
> +        requestCharacterQueue.maxConcurrentOperationCount = 10
Готово

2022-06-02 20:18 UTC, JuliaRuru commented on ViewControllers/RegistrationViewController.swift
> +
Убрала

2022-06-02 20:18 UTC, JuliaRuru commented on ViewControllers/LocationViewController.swift
> +        return CGFloat(height)
Fixed

2022-06-02 20:18 UTC, JuliaRuru commented on ViewControllers/LocationCells/LocationTableViewCell.swift
> +    }
Убрала

2022-06-02 20:18 UTC, JuliaRuru commented on Services/StorageManager/StorageManager.swift
> +import KeychainAccess
Убрала

2022-06-02 20:18 UTC, JuliaRuru commented on Services/StorageManager/ProfileStorageManager.swift
> +    func loadFromKeychain(key: StorageManager.StorageManagerKey) -> String?
Сделала, теперь получает только userId

2022-06-03 04:22 UTC, JuliaRuru commented on Services/NetworkManager/LocationNetworkManager.swift
> +//    func getCharacterList(url: String, completion: ((CharacterListResponse?, Error?) -> ())?)
Убрала

2022-06-03 05:00 UTC, JuliaRuru commented on Services/StorageManager/UserDefaultsStorageManager.swift
> +    func userDefaultsBool(key: StorageManager.StorageManagerKey) -> Bool
Сделала конкретные методы без ключей

2022-06-03 05:10 UTC, JuliaRuru commented on ViewControllers/LocationViewController.swift
> +        progressHUD.show(in: self.view)
Fixed

2022-06-03 05:12 UTC, JuliaRuru commented on ViewControllers/ResidentsViewController.swift
> +        group.enter()
Убрала

2022-06-03 05:18 UTC, JuliaRuru commented on hnh1/AppDelegate.swift
> +        }
Fixed

2022-06-03 06:36 UTC, JuliaRuru commented on ViewControllers/ResidentsViewController.swift
> +            heightDimension: .absolute(187))
убрала фиксированную ширину айтема, теперь хорошо

2022-06-03 11:04 UTC, JuliaRuru commented on ViewControllers/ResidentsViewController.swift
> +         if let cell = collectionView.dequeueReusableCell(withReuseIdentifier: ResidentsCollectionViewCell.className, for: indexPath) as? ResidentsCollectionViewCell {
добавила проверку

2022-06-03 12:40 UTC, NosferatuHnH commented on ViewControllers/LocationViewController.swift
> +        return CGFloat(height)
зачем каст? Зачем ретурн?

2022-06-03 12:42 UTC, NosferatuHnH commented on ViewControllers/LocationViewController.swift
> +        self.progressHUD.dismiss()
селф не нужен. Тут он сразу после начала запроса исчезнет. Если такой логикой рулить - лучше уж прятать его когда запрос выполнится

2022-06-03 12:47 UTC, NosferatuHnH commented on ViewControllers/ResidentsViewController.swift
> +         if let cell = collectionView.dequeueReusableCell(withReuseIdentifier: ResidentsCollectionViewCell.className, for: indexPath) as? ResidentsCollectionViewCell {
по имейджу вижу. Но немного не то. Сделай сперва ИДшник для персонажа (урла подойдёт), потом по его соотвествию подставляй данные о персонаже (втч айдишник картинки) и делай запрос на картинку. По соответствию ИДшника картинки подставляй картинку

2022-06-03 13:28 UTC, JuliaRuru commented on ViewControllers/LocationViewController.swift
> +        self.progressHUD.dismiss()
fixed

2022-06-03 15:33 UTC, JuliaRuru commented on ViewControllers/ResidentsViewController.swift
> +         if let cell = collectionView.dequeueReusableCell(withReuseIdentifier: ResidentsCollectionViewCell.className, for: indexPath) as? ResidentsCollectionViewCell {
готово

2022-06-03 15:37 UTC, JuliaRuru commented on ViewControllers/LocationViewController.swift
> +        return CGFloat(height)
fixed

2022-06-03 15:48 UTC, NosferatuHnH approved these changes

2022-06-03 15:52 UTC, merged